berkay:
  gateway:
    auth-service-uri: ${AUTH_SERVICE_URI}
    product-service-uri: ${PRODUCT_SERVICE_URI}
  cors:
    public-allowed-origins: ${PUBLIC_ALLOWED_ORIGINS}
    personnel-allowed-origins: ${PERSONNEL_ALLOWED_ORIGINS}

logging:
  level:
    root: WARN
    com.berkay: INFO
