berkay:
  gateway:
    auth-service-uri: http://localhost:8081
    product-service-uri: http://localhost:8082
  cors:
    public-allowed-origins: "*"
    personnel-allowed-origins:
      - http://localhost:5173
      - http://localhost:4174
