spring:
  application:
    name: api
  profiles:
    default: local
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

server:
  port: 8080

logging:
  level:
    root: INFO
    com.berkay: DEBUG
    org.springframework.cloud.gateway: DEBUG
