spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: berkay
    password: "1234"
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api/auth

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    org.hibernate.SQL: DEBUG
