spring:
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
    username: berkay
    password: "1234"
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/api/auth
  config:
    import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  level:
    root: INFO
    com.berkay: DEBUG
